version: '3.9'
services:
    web-api:
        image: ${PROJECT_ID}-img
        container_name: ${PROJECT_ID}
        build:
            context: .
            network: webnet
        ports:
            - 127.0.0.1:${WEB_API_PORT}:${WEB_API_PORT}
            - 127.0.0.1:${MOBILE_API_PORT}:${MOBILE_API_PORT}
            - 127.0.0.1:${SWAGGER_UI_PORT}:${SWAGGER_UI_PORT}
            - 127.0.0.1:${WEB_UI_PORT}:${WEB_UI_PORT}
            - 127.0.0.1:${WEB_SOCKET_PORT}:${WEB_SOCKET_PORT}
        networks:
            - webnet
        logging:
            driver: 'json-file'
            options:
                max-size: '8m'
                max-file: '10'
        restart: always
networks:
    webnet:
        name: webnet
        driver: bridge
