version: '3.9'
services:
    web-api:
        image: ${PROJECT_ID}-img
        container_name: ${PROJECT_ID}
        build:
            context: .
            network: webnet
        ports:
            - 127.0.0.1:${API_PORT}:${API_PORT}
            - 127.0.0.1:${WEB_PORT}:${WEB_PORT}
            - 127.0.0.1:${SOCKET_PORT}:${SOCKET_PORT}
        networks:
            - webnet
        logging:
            driver: 'json-file'
            options:
                max-size: '8m'
                max-file: '10'
        restart: always
networks:
    webnet:
        name: webnet
        driver: bridge
