export class ErrorCode {
    static SOMETHING_WRONG = 'SOMETHING_WRONG_ERR';
    static OTHER = 'OTHER_ERR';
    static NOT_SUPPORTED = 'NOT_SUPPORTED_ERR';
    static ACCESS_DENIED = 'ACCESS_DENIED_ERR';
    static DATA_NOT_FOUND = 'DATA_NOT_FOUND_ERR';
    static DATA_CANNOT_SAVE = 'DATA_CANNOT_SAVE_ERR';
    static DATA_CANNOT_UPLOAD = 'DATA_CANNOT_UPLOAD_ERR';
    static DATA_REQUIRED = 'DATA_REQUIRED_ERR';
    static DATA_INVALID = 'DATA_INVALID_ERR';
    static DATA_INCORRECT = 'DATA_INCORRECT_ERR';
    static DATA_EXISTED = 'DATA_EXISTED_ERR';
    static DATA_SENT = 'DATA_SENT_ERR';
    static DATA_NOT_EXISTS = 'DATA_NOT_EXISTS_ERR';
    static DATA_EXPIRED = 'DATA_EXPIRED_ERR';
    static DATA_NOT_ACTIVATED = 'DATA_NOT_ACTIVATED_ERR';
    static DATA_NOT_VERIFIED = 'DATA_NOT_VERIFIED_ERR';
}
